services:
  - type: web
    name: wildlife-incident-reporter
    env: python
    plan: free
    branch: main
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wildlife_db
          property: connectionString

databases:
  - name: wildlife_db
    plan: free